### ISSUE TITLE
why the result lose the hand ? it becomes black mask .

### ISSUE THREAD

**Issue by chenbolin-master** [nihaomiao/WACV23_TSNet#11]
![11](https://github.com/nihaomiao/WACV23_TSNet/assets/86581924/a9cbd0ac-6471-4718-88fa-a2169d8dd613)
![22](https://github.com/nihaomiao/WACV23_TSNet/assets/86581924/adb0300d-9916-4c9c-8815-f8c6dbe1732b)

why the result lose the hand ? it becomes black mask .

**Comment by nihaomiao** [comment]
Hi, @chenbolin-master, the reason may be the pre-processing [function](https://github.com/nihaomiao/WACV23_TSNet/blob/f19f9a09c32a722f879c42dc9b08c9c1a5da5dfa/dataset/dataset_video_pose.py#L162) or the cropping [function](https://github.com/nihaomiao/WACV23_TSNet/blob/f19f9a09c32a722f879c42dc9b08c9c1a5da5dfa/dataset/dataset_video_pose.py#L202) I used to make sure each image to be square. You may modify them to meet your need.
