### ISSUE TITLE
the result of training TS-Net on the new subject is  poor

### ISSUE THREAD

**Issue by chenbolin-master** [nihaomiao/WACV23_TSNet#13]
the result of training TS-Net on the new subject is  poor , 
LEARNING_RATE = 2e-4
training image num is 296 .
![1111](https://github.com/nihaomiao/WACV23_TSNet/assets/86581924/2ea14b46-82fa-4296-8231-d080ec3653a8)

and when the training image is same as testing image .
the result  is good,
so it need a large number of images includes different pose to train?
![22222](https://github.com/nihaomiao/WACV23_TSNet/assets/86581924/239971c6-8dd5-44a5-a451-eedaa4f8d76e)

**Comment by nihaomiao** [comment]
Hi, @chenbolin-master, for the new subject, you may need some images including different poses to ensure the good generalization ability of the model.
