### ISSUE TITLE
libraries versions + colab notebook

### ISSUE THREAD

**Issue by anty94** [nihaomiao/WACV23_TSNet#15]
Hi. could you please include something like requirements.txt into your project, so that installation of the necessary libraries would be easier? 
I would also like to add that this project seems very promising and a working colab notebook would be greatly appreciated by whole community. ;) Easily testable demo would surely bring in many new fans of this project. Thanks.

**Comment by nihaomiao** [comment]
Hi, @anty94, thanks a lot for your suggestions! I have used `pipreqs` to generate the `requirements.txt`. Your suggestion about creating colab version is also really helpful! I may make one when I am free. Thanks a lot for your interest in our work!
