### ISSUE TITLE
pre-processing of pose dataset

### ISSUE THREAD

**Issue by hacker009-sudo** [nihaomiao/WACV23_TSNet#17]
@nihaomiao please guide how do you get clean_unseen_video_dict.json and clean_video_dict.json ? I have tried to extract the key-points using openpose but it seems bit different from the json that you have provided under dataset folder.

**Comment by nihaomiao** [comment]
Hi, @hacker009-sudo, thanks for your interest in our work! I don't remember the details very clearly right now. But I first used OpenPose to generate the video_dict.json files and then I manually checked the pose estimation results of each video frame and deleted those bad results to produce the clean version.

**Comment by hacker009-sudo** [comment]
Thanks
