### ISSUE TITLE
where is the pose keypoint detector? 

### ISSUE THREAD

**Issue by AWangji** [nihaomiao/WACV23_TSNet#18]
Hi, thank you for your good project. But there is a question for me. I wanna know where the pose keypoint detector in your codes is. Or is there any tools or model that can transfer the pose keypoint into json file like yours in demo/dance_example/labels/00164/...json.
Thanks!

**Comment by nihaomiao** [comment]
Hi, @AWangji, I use [OpenPose](https://github.com/CMU-Perceptual-Computing-Lab/openpose).

**Comment by AWangji** [comment]
> Hi, @AWangji, I use [OpenPose](https://github.com/CMU-Perceptual-Computing-Lab/openpose).

hi, but openpose output has many formats. which do you use?
