### ISSUE TITLE
About Animation Character Dance

### ISSUE THREAD

**Issue by zcdliuwei** [nihaomiao/WACV23_TSNet#2]
What a wonderful work!
I would like to ask if it is possible to change the subject to anime characters, and then use the driving video of real person dancing to make anime characters dance?
Thank you and look forward to your reply

**Comment by zcdliuwei** [comment]
> Hi, @zcdliuwei, if you have the skeleton of the given character and the real person, and fine-tune the TS-Net on that character, I think it is possible.

Thank you for your reply
How to obtain the skeleton of an animation character? All I have seen are human skeleton extraction, but the extraction effect on animation characters is poor. Is there any reference material that can be recommended in this regard
In addition, we look forward to your training and fine-tuning code, as well as the pre training model
thanks again

**Comment by nihaomiao** [comment]
Hi, @zcdliuwei, I just google it and find this WACV'22 paper may be related to your goal, [Transfer Learning for Pose Estimation of Illustrated Characters](https://openaccess.thecvf.com/content/WACV2022/papers/Chen_Transfer_Learning_for_Pose_Estimation_of_Illustrated_Characters_WACV_2022_paper.pdf).

Yeah, I have been working on the demo recently. Hopefully, I can release it next month. 

Bests
Haomiao Ni

**Comment by zcdliuwei** [comment]
> 

Thank you very much for your reply

I will take a look at this article and try to use your code to fine-tune animation characters！
