### ISSUE TITLE
Fine-tuning on a new subject

### ISSUE THREAD

**Issue by alasokolova** [nihaomiao/WACV23_TSNet#21]
Hi, have you tried to fine-tune your pretrained model on a new subject?
How much data is needed for this and how long does it take to fine-tune the model so that it works well on a new subject?

**Comment by nihaomiao** [comment]
Hi, @alasokolova, thanks a lot for your interest in our work.  Depending on the complexity of the new subject movement, It is hard to answer how much data is needed and how long it takes. You may start with a single subject with a still background and simple motion to get to know these details.
