### ISSUE TITLE
Dear author, can you provide the code to obtain the data label?

### ISSUE THREAD

**Issue by mioyeah** [nihaomiao/WACV23_TSNet#3]

**Comment by nihaomiao** [comment]
Hi, @mioyeah , for the face label extraction, I use [dlib](https://pypi.org/project/dlib/) to extract 68 facial landmarks. For the body keypoints extraction, I use [OpenPose](https://github.com/CMU-Perceptual-Computing-Lab/openpose).

**Comment by mioyeah** [comment]
Well, thank you

**Comment by chenbolin-master** [comment]
the < https://github.com/CMU-Perceptual-Computing-Lab/openpose > includes C++ ， how to get body keypoints extraction only includes python ?
