### ISSUE TITLE
can you provide the link of dataset of Youtube-dance and FaceForensics ?

### ISSUE THREAD

**Issue by chenbolin-master** [nihaomiao/WACV23_TSNet#5]
can you provide the link of dataset of Youtube-dance and FaceForensics ?

**Comment by nihaomiao** [comment]
Hi, @chenbolin-master, You may refer to this [github repo](https://github.com/NVlabs/few-shot-vid2vid/blob/009e23f17f4ce1f227fdb4bbf50f81f706cd2c04/data/preprocess/youTube_playlist.txt#L2) for downloading the Youtube-dance dataset. They also provide codes for downloading videos from Youtube. For FaceForensics dataset, you can refer to this [link](https://github.com/ondyari/FaceForensics/tree/original). Thanks a lot!
