### ISSUE TITLE
How to pre-process pose dataset

### ISSUE THREAD

**Issue by myshelter-c** [nihaomiao/WACV23_TSNet#6]
Thank you for a very good job.
I don't know how to get clean_unseen_video_dict.json and clean_video_dict.json to train the model.
Can you tell me the specific steps or code?

**Comment by nihaomiao** [comment]
Hi, @myshelter-c, thanks a lot for your interest in our work! These JSON files just contain the paths to the video frames and their corresponding skeleton keypoints extracted by OpenPose for loading data. You don't need to follow our codes when writing your own dataloader.
