### ISSUE TITLE
Model training

### ISSUE THREAD

**Issue by jasonwongw** [nihaomiao/WACV23_TSNet#8]
I see that the label_nc in the train_pose.py is 25. When the model is trained, are there 21 key points of the hand?

**Comment by nihaomiao** [comment]
Hi, @jasonwongw, thanks for your interest! We don't use the hand keypoints because they are not very accurate.

**Comment by jasonwongw** [comment]
Thanks for your reply.
In video frames, it is difficult to extract hand keys.
